apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  labels:
    app: gslb
  name: yesserv80
spec:
  ingressClassName: avi-lb
  rules:
  - host: yesserv80.c46.avilab.top
    http:
      paths:
      - path: /
        pathType: Prefix    
        backend:
          service:
            name: yesserv
            port:
              number: 80
