apiVersion: v1
kind: Service
metadata:
  labels:
    app: gslb
  name: avisvclb
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: avi-server
