apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: insecure
spec:
  rules:
  - host: app1.ako.avilab.me
    http:
      paths:
      - backend:
          serviceName: s1
          servicePort: 8080
