apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app: gslb
  name: yesserv_insecure
spec:
  rules:
  - host: yessrv80.ako.avilab.me
    http:
      paths:
      - backend:
          serviceName: yesserv
          servicePort: 80