apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app: gslb
  name: yesservinsecure
spec:
  rules:
  - host: yessrv80.ako.avilab.fun
    http:
      paths:
      - backend:
          serviceName: yesserv
          servicePort: 80