apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "avi"
  labels:
    app: gslb
  name: yesservinsecure
spec:
  rules:
  - host: yesserv80.ako.avilab.fun
    http:
      paths:
      - backend:
          serviceName: yesserv
          servicePort: 80
