apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
spec:
  selector:
    matchLabels:
      app: blue
  replicas: 2
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: blue
        image: harbor-repo.vmware.com/dockerhub-proxy-cache/alexfeig/bluegreen:latest
        ports:
        - containerPort: 5000
        env:
        - name: app_color
          value: "blue"
---
apiVersion: v1
kind: Service
metadata:
  name: blue
spec:
  ports:
  - name: http 
    port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: blue
