apiVersion: ako.vmware.com/v1beta1
kind: HostRule
metadata:
  name: hostrule1
  namespace: default
spec:
  virtualhost:
    fqdn: "*.az45.avilab.top"
    fqdnType: Wildcard
    enableVirtualHost: true
    tls: # optional
      sslKeyCertificate:
        name: System-Default-Cert-EC
        type: ref
        alternateCertificate:
          name: System-Default-Cert
          type: ref
      sslProfile: System-Standard-PFS
      termination: edge
    gslb:
      fqdn: santagslb.avilab.top
      includeAliases: false
#    httpPolicy: 
#      policySets:
#      - avi-secure-policy-ref
#      overwrite: false
#    datascripts:
#    - avi-datascript-redirect-app1
    wafPolicy: DetectionMode
#    applicationProfile: avi-app-ref
#    icapProfile: 
#    - avi-icap-ref
    analyticsProfile: CustomAnalytics
#    errorPageProfile: avi-errorpage-ref
    analyticsPolicy: # optional
      fullClientLogs:
        enabled: true
        throttle: HIGH
      logAllHeaders: true
#    tcpSettings:
#      listeners:
#     - port: 8081
#      - port: 6443
#        enableSSL: true
#      loadBalancerIP: 10.10.10.1
#    aliases: # optional
#    -  bar.com
#    -  baz.com